databases:
  - name: helloworld-db
    databaseName: helloworld
    user: helloworld

services:
  - type: web
    name: helloworld
    env: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn helloworld.wsgi:application --workers 4 --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: helloworld-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.0